<?php
/**
 * Category sidebar
 *
 * @var $block Kashyap\CategorySidebar\Block\CategorySidebar
 */
$categories = $block->getCategories();
?>
<?php if($categories) : ?>
    <?php $categorydepth = $this->getCateLavel(); ?>
    <h3><?php echo __('Categories'); ?></h3>
    <ul class="ks-list">
        <?php foreach ( $categories as $category ) : ?>
            <li class="level0<?= ($block->isActive($category) ? ' active' : ''); ?>">
                <a href="<?= $block->getCategoryUrl($category); ?>" title="<?= $category->getName(); ?>" class="<?= ($block->isActive($category) ? ' active' : ''); ?>">
                    <?= $category->getName(); ?>
                </a>
                <?php 
                    $level = $category->getLevel();
                    if ( $category->hasChildren() && $level <= $categorydepth) : ?>
                        <span class="expand"><?= $block->isActive($category) ? '<i class="fa fa-minus"></i>' : '<i class="fa fa-plus"></i>'; ?></span>
                <?php endif; ?>

                <?= $block->getChildCategoryView($category); ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
    	require(['jquery','ks_categorySidebar'], function ($) {});
    </script>
<?php endif; ?>